### ISSUE TITLE
Forward slash being replaced by back slash in command line arguments

### ISSUE THREAD

**Issue by jcageman** [milostosic/rdebug#2]
Hi,  

Thanks for the great tool! Lets jump right to the issue i am having. I have an application which contains a forward slash in the arguments passed to the application. Example: myapp.exe default processtype:1/3
The problem is that MTuner actually calls the process as myapp.exe default processtype:1\3
Note the change of forward slash to backslash here.
I can currently work around it by making the target process parse the backslash as well. This issue is low priority for me, but i thought it would be good to report it at least.

I suspect the problem is in rdebug/src/process.cpp. The arguments passed are parsed as a path due to `rtm::MultiToWide path(_path);` Its not an actual path but a path combined with arguments, i think you have to parse those separately.

Kind regards,

Jacob

**Comment by milostosic** [comment]
Hi,
Thanks for reporting this! I just pushed a fix for this, command line arguments were indeed treated as a path. I'll post a new MTuner binary release later today.
